### ISSUE TITLE
problem with main package class 

### ISSUE THREAD

**Issue by Raghdkun** [ged-flod/google_gemini#1]
i have this issue when i type pub get commend run the debug 
The plugin `google_gemini` doesn't have a main class defined in /home/raghdkun/.pub-cache/hosted/pub.dev/google_gemini-0.0.3/android/src/main/java/com/wexende/google_gemini/GoogleGeminiPlugin.java or /home/raghdkun/.pub-cache/hosted/pub.dev/google_gemini-0.0.3/android/src/main/kotlin/com/wexende/google_gemini/GoogleGeminiPlugin.kt. This is likely to due to an incorrect `androidPackage: com.wexende.google_gemini` or `mainClass` entry in the plugin's pubspec.yaml.
If you are the author of this plugin, fix the `androidPackage` entry or move the main class to any of locations used above. Otherwise, please contact the author of this plugin and consider using a different plugin in the meanwhile.

**Comment by TheBeaconCrafter** [comment]
I've got the same issue. Have you found a fix yet?

**Comment by ged-flod** [comment]
Hi, I just fixed the issue on version 0.0.6. 
[checkout  👈🏼](https://pub.dev/packages/google_gemini)

**Comment by Raghdkun** [comment]
hello guys i fix it by running a vpn with good internet connection
