### ISSUE TITLE
problem with getting api key

### ISSUE THREAD

**Issue by Colin-Stark** [ged-flod/google_gemini#2]
![image](https://github.com/ged-flod/google_gemini/assets/68123937/92311f8a-a18c-494c-a24e-4d5b1193ebe4)

I don't know why i am being restricted

**Comment by ged-flod** [comment]
Dear @Colin-Stark  this error is not from this package but from Google AI Studio. Let's see the source.

1. Current Location: 
Gemini Pro is currently in Early Access and only available in certain regions like the US. If you're trying to access it from outside an eligible region, you'll encounter this restriction.

2.  Google AI Studio Permissions: 
Make sure you have the necessary permissions within Google AI Studio to access Gemini API keys. Check with your organization's administrator or project owner to ensure you have appropriate access levels.
